/**
 * デザインシステム - アイコン関連型定義
 */

// すべてのアイコン名のリスト
export const ALL_ICON_TYPES = [
  // REGULAR
  'dot',
  'info-circle',
  'info-triangle',
  'x',
  'hamburger',
  'person',
  'employee',
  'magnifying-glass',
  'eye',
  'eye-slashed',
  'comment-check',
  'bell',
  'lock',
  'unlock',
  'expand',
  'calendar',
  'chevron-down',
  'chevron-up',
  'chevron-left',
  'chevron-right',
  'chevrons-left',
  'chevrons-right',
  'arrow-up-right',
  'arrow-in',
  'sync-pull',
  'sync-push',
  'arrow-rotate',
  'arrow-turn-left',
  'arrow-u-turn',
  'door-out',
  'funnel',
  'gear',
  'home',
  'dashboard',
  'chart-bar',
  'list',
  'file',
  'survey',
  'check',
  'check-circle',
  'x-circle',
  'keyboard',
  'palette',
  'brush',
  'sliders',
  'diamond',
  'paint-roller',
  'chat',
  'clock',
  'folder',
  'users-group',
  'trend-up',
  'trend-up-right',
  'trend-right',
  'trend-down-right',
  'trend-down',
  'trash',
  'save',
  'star',
  'star-filled',
  'cloud-upload',
  'inbox',
  'archive',
  // メディアプレイヤー
  'volume-off',
  'volume-low',
  'volume-high',
  'fullscreen',
  'fullscreen-exit',
  'shuffle',
  'skip-forward',
  'sidebar',
  // 議事録・音声関連アイコン
  'transcript-doc',   // メイン: 音声波形+ドキュメント
  'audio-wave',       // M字波形（ロゴ的）
  'mic-text',         // マイク+テキストライン
  'play-doc',         // 再生+ドキュメント
  'chat-wave',        // 吹き出し波形
  'shield-audio',     // シールド型
  // LOADING
  'spinner',
  'spinner-thin',
  'spinner-thick',
  'loading-dots',
  'loading-dots-fade',
  'loading-pulse',
  'loading-pulse-ring',
  'loading-bars',
  'loading-bounce',
  'loading-clock',
  'loading-wifi',
  'loading-orbit',
  'loading-morph',
  'loading-progress',
  'loading-half',
  'loading-dash',
  'loading-scale-pulse',
  'loading-flip',
  'loading-square',
  'loading-triangle',
  'loading-cross',
  'loading-star',
  'loading-hexagon',
  'loading-dna',
  'loading-ripple',
  'loading-infinity',
  'loading-atom',
  'loading-heartbeat',
  'loading-hourglass',
  'loading-gears',
  'loading-wave',
  'loading-radar',
  'loading-cube3d',
  'loading-cube3d-glow',
  'loading-rings',
  'loading-eclipse',
  'loading-interview',
  'loading-prism',
  'loading-particles',
  'loading-comet',
  'loading-magnet',
  'loading-braid',
  'loading-vortex',
] as const;

// ローディングアイコン名のリスト
export const LOADING_ICON_TYPES = [
  'spinner',
  'spinner-thin',
  'spinner-thick',
  'loading-dots',
  'loading-dots-fade',
  'loading-pulse',
  'loading-pulse-ring',
  'loading-bars',
  'loading-bounce',
  'loading-clock',
  'loading-wifi',
  'loading-orbit',
  'loading-morph',
  'loading-progress',
  'loading-half',
  'loading-dash',
  'loading-scale-pulse',
  'loading-flip',
  'loading-square',
  'loading-triangle',
  'loading-cross',
  'loading-star',
  'loading-hexagon',
  'loading-dna',
  'loading-ripple',
  'loading-infinity',
  'loading-atom',
  'loading-heartbeat',
  'loading-hourglass',
  'loading-gears',
  'loading-wave',
  'loading-radar',
  'loading-cube3d',
  'loading-cube3d-glow',
  'loading-rings',
  'loading-eclipse',
  'loading-interview',
  'loading-prism',
  'loading-particles',
  'loading-comet',
  'loading-magnet',
  'loading-braid',
  'loading-vortex',
] as const;

// 型定義
export type IconName = (typeof ALL_ICON_TYPES)[number];
export type LoadingIconName = (typeof LOADING_ICON_TYPES)[number];

// 型ガード関数
export const isLoadingIcon = (iconName: string): boolean =>
  iconName.startsWith('loading-') || iconName.startsWith('spinner');

export const isRegularIcon = (iconName: string): boolean =>
  !iconName.startsWith('loading-') && !iconName.startsWith('spinner');
