// app から直 import されていた lucide-react アイコンを、catalog の `Icon` 経由で
// 描画するための name→component registry。
//
// ここに **明示 named import** で登録した名前だけ `<Icon name="..." />` で使える。
// `import { icons } from 'lucide-react'` のような全量 import は tree-shaking を壊す
// ため禁止（新規アイコンが要るときはこの map に 1 行足す）。
//
// 衝突名（`bell` / `award` / `check` / `clock` / `lock` / `star` / `target` /
// `check-circle` / `chevron-down|left|right` / `folder` 等）は既に
// `constants/icons.ts` の `ICON_PATHS`（独自 SVG）にあり、`Icon` は独自を優先する。
// よって衝突名はここに **登録しない**（1 アプリ 1 アイコンに統一）。

import {
  Activity,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BadgeCheck,
  Ban,
  BarChart3,
  BookOpen,
  Building2,
  CalendarClock,
  Camera,
  ClipboardCheck,
  ClipboardEdit,
  ClipboardList,
  Columns3,
  Construction,
  Database,
  Download,
  FileBadge,
  FileBadge2,
  FileClock,
  FileDown,
  FileText,
  Flag,
  FolderCog,
  Globe,
  GraduationCap,
  History,
  House,
  Image,
  KeyRound,
  Layers,
  LayoutGrid,
  Library,
  Link,
  LogOut,
  Mail,
  PanelLeftClose,
  Play,
  PlayCircle,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  TrendingUp,
  Upload,
  UserCircle,
  UserPlus,
  UserRound,
  Users,
  type LucideIcon,
} from 'lucide-react'

/** name(kebab) → lucide component。衝突名は登録しない（独自 SVG 優先）。 */
export const LUCIDE_ICONS = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  ban: Ban,
  'bar-chart-3': BarChart3,
  'book-open': BookOpen,
  'building-2': Building2,
  'calendar-clock': CalendarClock,
  camera: Camera,
  'clipboard-check': ClipboardCheck,
  'clipboard-edit': ClipboardEdit,
  'clipboard-list': ClipboardList,
  'columns-3': Columns3,
  construction: Construction,
  database: Database,
  download: Download,
  'file-badge': FileBadge,
  'file-badge-2': FileBadge2,
  'file-clock': FileClock,
  'file-down': FileDown,
  'file-text': FileText,
  flag: Flag,
  'folder-cog': FolderCog,
  globe: Globe,
  'graduation-cap': GraduationCap,
  history: History,
  house: House,
  image: Image,
  'key-round': KeyRound,
  layers: Layers,
  'layout-grid': LayoutGrid,
  library: Library,
  link: Link,
  'log-out': LogOut,
  mail: Mail,
  'panel-left-close': PanelLeftClose,
  play: Play,
  'play-circle': PlayCircle,
  scale: Scale,
  'scroll-text': ScrollText,
  settings: Settings,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  'trending-up': TrendingUp,
  upload: Upload,
  'user-circle': UserCircle,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
} satisfies Record<string, LucideIcon>

/** registry に登録された lucide 由来のアイコン名 */
export type LucideIconName = keyof typeof LUCIDE_ICONS
